### PR TITLE
add items programmetically feature

### PR DESCRIPTION
**Pull request by ch-muhammad-adil**

### CODE REVIEW

**Comment by rubensousa** [comment]
Thanks :)

**Comment by ch-muhammad-adil** [comment]
You are most welcome, Please update its Gradle plugin so I can use that one. ;)

**Comment by rubensousa** [comment]
I'm just adding some extra code and testing so I can release this :)

**Comment by ch-muhammad-adil** [comment]
Please do update me when you release.

**Comment by rubensousa** [comment]
Can you check the sample and the addItem API again? It should behave better now.

**Comment by ch-muhammad-adil** [comment]
Let me try it.

**Comment by ch-muhammad-adil** [comment]
API is really simple now. 
I have given a comment on one of your commit where you have removed a function. I hope you understand my idea. There can be another option we can give to developers that is loading icons from URL and inside the Library APIs we can use any Image Loader Library. This will also allow developers to add items dynamically. (Just an idea)

**Comment by rubensousa** [comment]
Ok, I can also do that. Thanks once again :)

**Comment by ch-muhammad-adil** [comment]
Sorry I have tested, its fine so far. just need to add option for bitmap and icon URL.

**Comment by ch-muhammad-adil** [comment]
So far I am able to do this way.. It working fine in my case and I am able to achieve my task. (y) Thanks



    ```
private void createShareMenu() {
        BottomSheetBuilder builder = new BottomSheetBuilder(MyCardsActivity.this, R.style.AppTheme_BottomSheetDialog_Custom)
                .setMode(BottomSheetBuilder.MODE_GRID)
//                .setMenu(R.menu.share_item_menu)
                .setItemClickListener(new BottomSheetItemClickListener() {
                    @Override
                    public void onBottomSheetItemClick(MenuItem item) {

                    }
                });
        for (MenuItem menuItem : ListOfMenuItems) {
            builder.addItem(menuItem.getMenuId(), menuItem.getName(), new BitmapDrawable(getResources(), menuItem.getBitmap()));
        }
        BottomSheetMenuDialog dialog = builder.createDialog();
        dialog.show();
    }

```

**Comment by rubensousa** [comment]
If you managed to do it, I prefer keeping the API with Drawable and DrawableRes only :)

**Comment by ch-muhammad-adil** [comment]
Yeah! I think its all good now. :)

**Comment by rubensousa** [comment]
Released on 1.6.0.

**Pull request merged**
